export var stationsByLine = [
	{
		name: "Bakerloo",
		not_guessed: [
			"Baker Street",
			"Charing Cross",
			"Elephant & Castle",
			"Embankment",
			"Edgware Road (Bakerloo)",
			"Harrow & Wealdstone",
			"Harlesden",
			"Kenton",
			"Kilburn Park",
			"Kensal Green",
			"Lambeth North",
			"Maida Vale",
			"Marylebone",
			"North Wembley",
			"Oxford Circus",
			"Paddington",
			"Piccadilly Circus",
			"Queen's Park",
			"Regent's Park",
			"Stonebridge Park",
			"South Kenton",
			"Willesden Junction",
			"Warwick Avenue",
			"Waterloo",
			"Wembley Central"
		],
		guessed: []
	},
	{
		name: "Central",
		not_guessed: [
			"Barkingside",
			"Buckhurst Hill",
			"Bethnal Green",
			"Bond Street",
			"Bank",
			"Chancery Lane",
			"Chigwell",
			"Debden",
			"East Acton",
			"Ealing Broadway",
			"Epping",
			"Fairlop",
			"Greenford",
			"Grange Hill",
			"Gants Hill",
			"Holborn",
			"Hanger Lane",
			"Hainault",
			"Holland Park",
			"Loughton",
			"Lancaster Gate",
			"Liverpool Street",
			"Leyton",
			"Leytonstone",
			"Marble Arch",
			"Mile End",
			"North Acton",
			"Newbury Park",
			"Notting Hill Gate",
			"Northolt",
			"Oxford Circus",
			"Perivale",
			"Queensway",
			"Redbridge",
			"Ruislip Gardens",
			"Roding Valley",
			"Shepherd's Bush (Central)",
			"Snaresbrook",
			"St. Paul's",
			"South Ruislip",
			"Stratford",
			"South Woodford",
			"Tottenham Court Road",
			"Theydon Bois",
			"White City",
			"Woodford",
			"West Ruislip",
			"Wanstead",
			"West Acton"
		],
		guessed: []
	},
	{
		name: "Circle",
		not_guessed: [
			"Aldgate",
			"Barbican",
			"Blackfriars",
			"Baker Street",
			"Bayswater",
			"Cannon Street",
			"Embankment",
			"Edgware Road (Circle Line)",
			"Euston Square",
			"Farringdon",
			"Goldhawk Road",
			"Great Portland Street",
			"Gloucester Road",
			"Hammersmith (H&C Line)",
			"High Street Kensington",
			"King's Cross St. Pancras",
			"Ladbroke Grove",
			"Latimer Road",
			"Liverpool Street",
			"Moorgate",
			"Monument",
			"Mansion House",
			"Notting Hill Gate",
			"Paddington",
			"Paddington (H&C Line)-Underground",
			"Royal Oak",
			"Shepherd's Bush Market",
			"St. James's Park",
			"South Kensington",
			"Sloane Square",
			"Temple",
			"Tower Hill",
			"Victoria",
			"Wood Lane",
			"Westminster",
			"Westbourne Park"
		],
		guessed: []
	},
	{
		name: "District",
		not_guessed: [
			"Acton Town",
			"Aldgate East",
			"Bromley-by-Bow",
			"Becontree",
			"Blackfriars",
			"Barking",
			"Barons Court",
			"Bow Road",
			"Bayswater",
			"Cannon Street",
			"Chiswick Park",
			"Dagenham East",
			"Dagenham Heathway",
			"Ealing Broadway",
			"Ealing Common",
			"Earl's Court",
			"East Ham",
			"Embankment",
			"Elm Park",
			"East Putney",
			"Edgware Road (Circle Line)",
			"Fulham Broadway",
			"Gunnersbury",
			"Gloucester Road",
			"Hornchurch",
			"Hammersmith (Dist&Picc Line)",
			"High Street Kensington",
			"Kensington (Olympia)",
			"Kew Gardens",
			"Mile End",
			"Monument",
			"Mansion House",
			"Notting Hill Gate",
			"Paddington",
			"Plaistow",
			"Parsons Green",
			"Putney Bridge",
			"Richmond",
			"Ravenscourt Park",
			"Stamford Brook",
			"Southfields",
			"Stepney Green",
			"St. James's Park",
			"South Kensington",
			"Sloane Square",
			"Temple",
			"Turnham Green",
			"Tower Hill",
			"Upminster Bridge",
			"Upton Park",
			"Upminster",
			"Upney",
			"Victoria",
			"West Brompton",
			"West Ham",
			"Wimbledon",
			"Wimbledon Park",
			"West Kensington",
			"Whitechapel",
			"Westminster"
		],
		guessed: []
	},
	{
		name: "Hammersmith & City",
		not_guessed: [
			"Aldgate East",
			"Bromley-by-Bow",
			"Barbican",
			"Barking",
			"Baker Street",
			"Bow Road",
			"East Ham",
			"Edgware Road (Circle Line)",
			"Euston Square",
			"Farringdon",
			"Goldhawk Road",
			"Great Portland Street",
			"Hammersmith (H&C Line)",
			"King's Cross St. Pancras",
			"Ladbroke Grove",
			"Latimer Road",
			"Liverpool Street",
			"Mile End",
			"Moorgate",
			"Paddington (H&C Line)-Underground",
			"Plaistow",
			"Royal Oak",
			"Shepherd's Bush Market",
			"Stepney Green",
			"Upton Park",
			"West Ham",
			"Wood Lane",
			"Whitechapel",
			"Westbourne Park"
		],
		guessed: []
	},
	{
		name: "Jubilee",
		not_guessed: [
			"Bermondsey",
			"Bond Street",
			"Baker Street",
			"Canning Town",
			"Canons Park",
			"Canada Water",
			"Canary Wharf",
			"Dollis Hill",
			"Finchley Road",
			"Green Park",
			"Kilburn",
			"Kingsbury",
			"London Bridge",
			"Neasden",
			"North Greenwich",
			"Queensbury",
			"St. John's Wood",
			"Stratford",
			"Stanmore",
			"Swiss Cottage",
			"Southwark",
			"West Ham",
			"West Hampstead",
			"Willesden Green",
			"Waterloo",
			"Westminster",
			"Wembley Park"
		],
		guessed: []
	},
	{
		name: "Metropolitan",
		not_guessed: [
			"Aldgate",
			"Amersham",
			"Barbican",
			"Baker Street",
			"Chalfont & Latimer",
			"Chesham",
			"Croxley",
			"Chorleywood",
			"Eastcote",
			"Euston Square",
			"Farringdon",
			"Finchley Road",
			"Great Portland Street",
			"Hillingdon",
			"Harrow-on-the-Hill",
			"Ickenham",
			"King's Cross St. Pancras",
			"Liverpool Street",
			"Moorgate",
			"Moor Park",
			"North Harrow",
			"Northwick Park",
			"Northwood",
			"Northwood Hills",
			"Pinner",
			"Preston Road",
			"Rickmansworth",
			"Ruislip Manor",
			"Ruislip",
			"Rayners Lane",
			"Uxbridge",
			"Watford",
			"West Harrow",
			"Willesden Green",
			"Wembley Park"
		],
		guessed: []
	}, {
		name: "Northern",
		not_guessed: [
			"Battersea Power Station",
			"Archway",
			"Angel",
			"Balham",
			"Bank",
			"Borough",
			"Burnt Oak",
			"Brent Cross",
			"Belsize Park",
			"Chalk Farm",
			"Charing Cross",
			"Colindale",
			"Clapham Common",
			"Clapham North",
			"Clapham South",
			"Colliers Wood",
			"Camden Town",
			"Elephant & Castle",
			"East Finchley",
			"Edgware",
			"Embankment",
			"Euston",
			"Finchley Central",
			"Goodge Street",
			"Golders Green",
			"High Barnet",
			"Hendon Central",
			"Highgate",
			"Hampstead",
			"Kennington",
			"Kentish Town",
			"King's Cross St. Pancras",
			"London Bridge",
			"Leicester Square",
			"Morden",
			"Moorgate",
			"Mill Hill East",
			"Mornington Crescent",
			"Old Street",
			"Oval",
			"Stockwell",
			"South Wimbledon",
			"Totteridge & Whetstone",
			"Tooting Bec",
			"Tooting Broadway",
			"Tottenham Court Road",
			"Tufnell Park",
			"West Finchley",
			"Waterloo",
			"Woodside Park",
			"Warren Street",
			"Nine Elms"
		],
		guessed: []
	},
	{
		name: "Piccadilly",
		not_guessed: [
			"Acton Town",
			"Alperton",
			"Arnos Grove",
			"Arsenal",
			"Bounds Green",
			"Boston Manor",
			"Barons Court",
			"Caledonian Road",
			"Covent Garden",
			"Cockfosters",
			"Eastcote",
			"Ealing Common",
			"Earl's Court",
			"Finsbury Park",
			"Green Park",
			"Gloucester Road",
			"Holborn",
			"Hillingdon",
			"Hatton Cross",
			"Hyde Park Corner",
			"Heathrow Terminal 4",
			"Heathrow Terminal 5",
			"Heathrow Terminals 2 & 3",
			"Hammersmith (Dist&Picc Line)",
			"Hounslow Central",
			"Hounslow East",
			"Hounslow West",
			"Holloway Road",
			"Ickenham",
			"Knightsbridge",
			"King's Cross St. Pancras",
			"Leicester Square",
			"Manor House",
			"North Ealing",
			"Northfields",
			"Oakwood",
			"Osterley",
			"Piccadilly Circus",
			"Park Royal",
			"Ruislip Manor",
			"Ruislip",
			"Russell Square",
			"Rayners Lane",
			"South Ealing",
			"Southgate",
			"South Harrow",
			"South Kensington",
			"Sudbury Hill",
			"Sudbury Town",
			"Turnham Green",
			"Turnpike Lane",
			"Uxbridge",
			"Wood Green"
		],
		guessed: []
	},
	{
		name: "Victoria",
		not_guessed: [
			"Blackhorse Road",
			"Brixton",
			"Euston",
			"Finsbury Park",
			"Green Park",
			"Highbury & Islington",
			"King's Cross St. Pancras",
			"Oxford Circus",
			"Pimlico",
			"Stockwell",
			"Seven Sisters",
			"Tottenham Hale",
			"Victoria",
			"Vauxhall",
			"Warren Street",
			"Walthamstow Central"
		],
		guessed: []
	},
	{
		name: "Waterloo & City",
		not_guessed: [
			"Bank",
			"Waterloo"
		],
		guessed: []
	}
];